import glob
import logging
import os
import platform
import threading
import time
import uuid

logger = logging.getLogger(__name__)


TRADE_OPS = {"OPEN", "PENDING", "MODIFY", "CANCEL", "CLOSE"}


def _command_op(cmd_str):
    return str(cmd_str).split("|", 1)[0].strip().upper()


def _looks_like_float(value):
    try:
        float(value)
        return True
    except (TypeError, ValueError):
        return False


def _response_matches_command(op, response):
    """Reject delayed responses from a previous command on the same IPC lane."""
    if not response:
        return False

    op = str(op).upper()
    parts = str(response).split("|")

    if response == "OK|Alive":
        return op == "ECHO"
    if response.startswith("OK|CAPS|"):
        return op == "CAPS"
    if response == "OK|MODIFIED":
        return op == "MODIFY"
    if response == "OK|CANCELED":
        return op == "CANCEL"

    if response.startswith("ERR|HIST|") or response in {
        "ERR|BAD_HIST_BARS",
        "ERR|HIST_SYMBOL_SELECT",
    }:
        return op == "HIST"
    if response == "ERR|INFO_TICK":
        return op == "INFO"
    if response == "ERR|BAD_OPEN_TYPE":
        return op == "OPEN"
    if response == "ERR|BAD_PENDING_TYPE":
        return op == "PENDING"
    if response == "ERR|POSITION_NOT_FOUND":
        return op in {"POSITION", "MODIFY", "CLOSE"}
    if response.startswith("ERR|"):
        # Numeric broker retcodes are generated by trade commands.
        if len(parts) >= 2 and parts[1].isdigit():
            return op in TRADE_OPS
        # Generic bridge errors are not command-specific.
        return True

    if not response.startswith("OK"):
        return False
    if response == "OK":
        return op in {"POSITIONS", "ORDERS"}

    if op == "HIST":
        return len(parts) >= 2 and "," in parts[1]
    if op == "INFO":
        return len(parts) >= 13 and all("," not in item for item in parts[1:13])
    if op in {"POSITIONS", "POSITION", "ORDERS"}:
        return len(parts) >= 2 and "," in parts[1]
    if op in {"OPEN", "PENDING"}:
        return len(parts) >= 3 and parts[1].isdigit() and _looks_like_float(parts[2])
    if op == "CLOSE":
        return len(parts) >= 6 and parts[1].isdigit()
    return True


def _configured_files_dir():
    for env_name in ("EA_BRIDGE_FILES_DIR", "MT5_FILES_DIR"):
        value = os.environ.get(env_name)
        if value:
            return os.path.expandvars(os.path.expanduser(value))
    try:
        from live_config import EA_BRIDGE_FILES_DIR
    except Exception:
        return None
    if EA_BRIDGE_FILES_DIR:
        return os.path.expandvars(os.path.expanduser(str(EA_BRIDGE_FILES_DIR)))
    return None


def _windows_terminal_files_dirs():
    appdata = os.environ.get("APPDATA")
    if appdata:
        terminal_root = os.path.join(appdata, "MetaQuotes", "Terminal")
    else:
        user_profile = os.environ.get("USERPROFILE", os.path.expanduser("~"))
        terminal_root = os.path.join(user_profile, "AppData", "Roaming", "MetaQuotes", "Terminal")
    pattern = os.path.join(terminal_root, "*", "MQL5", "Files")
    paths = [path for path in glob.glob(pattern) if os.path.isdir(path)]

    def score(path):
        mql5_dir = os.path.dirname(path)
        experts_dir = os.path.join(mql5_dir, "Experts")
        has_s18_bridge = int(
            os.path.isfile(os.path.join(experts_dir, "BotBridge_s18.ex5"))
            or os.path.isfile(os.path.join(experts_dir, "BotBridge_s18.mq5"))
        )
        try:
            mtime = os.path.getmtime(path)
        except OSError:
            mtime = 0.0
        return (has_s18_bridge, mtime)

    return sorted(paths, key=score, reverse=True)


def resolve_files_dir():
    configured = _configured_files_dir()
    if configured:
        return configured
    if platform.system() == "Windows":
        candidates = _windows_terminal_files_dirs()
        if candidates:
            return candidates[0]
        return r"C:\Program Files\MetaTrader 5\MQL5\Files"
    return "/root/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Files"


class EABridgeServer:
    def __init__(self, files_dir=None):
        if files_dir is None:
            files_dir = resolve_files_dir()

        self.bridge_dir = files_dir
        self.cmd_file = os.path.join(
            self.bridge_dir, os.environ.get("EA_BRIDGE_COMMAND_FILE", "cmd_s18.txt")
        )
        self.res_file = os.path.join(
            self.bridge_dir, os.environ.get("EA_BRIDGE_RESPONSE_FILE", "res_s18.txt")
        )
        self.heartbeat_file = os.path.join(
            self.bridge_dir, os.environ.get("EA_BRIDGE_HEARTBEAT_FILE", "heartbeat_s18.txt")
        )
        self.lock_file = os.path.join(
            self.bridge_dir, os.environ.get("EA_BRIDGE_LOCK_FILE", "ea_bridge_s18.lock")
        )
        self.lock_stale_seconds = float(os.environ.get("EA_BRIDGE_LOCK_STALE_SECONDS", "30"))
        self._command_lock = threading.Lock()

        logger.info("File IPC Bridge initialized at %s", self.bridge_dir)
        logger.info(
            "File IPC Bridge files cmd=%s res=%s lock=%s",
            self.cmd_file,
            self.res_file,
            self.lock_file,
        )

    def _acquire_ipc_lock(self, timeout):
        deadline = time.monotonic() + max(1.0, float(timeout))
        token = f"{os.getpid()}|{time.time():.6f}|{uuid.uuid4().hex}"
        while time.monotonic() < deadline:
            try:
                fd = os.open(self.lock_file, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(fd, token.encode("ascii", errors="replace"))
                os.fsync(fd)
                return fd
            except FileExistsError:
                try:
                    age = time.time() - os.path.getmtime(self.lock_file)
                except OSError:
                    age = 0.0
                if age > self.lock_stale_seconds:
                    try:
                        os.remove(self.lock_file)
                        logger.warning("Removed stale EA bridge IPC lock: %s", self.lock_file)
                    except OSError:
                        pass
                time.sleep(0.05)
            except FileNotFoundError:
                logger.error("EA bridge directory does not exist: %s", self.bridge_dir)
                return None
            except Exception as exc:
                logger.error("Could not acquire EA bridge IPC lock: %s", exc)
                return None
        return None

    def _release_ipc_lock(self, fd):
        try:
            os.close(fd)
        except Exception:
            pass
        try:
            os.remove(self.lock_file)
        except FileNotFoundError:
            pass
        except Exception as exc:
            logger.warning("Could not remove EA bridge IPC lock: %s", exc)

    def _clear_command_file(self):
        try:
            with open(self.cmd_file, "w") as f:
                f.write("")
                f.flush()
                os.fsync(f.fileno())
        except Exception as exc:
            logger.warning("Could not clear EA bridge command file: %s", exc)

    def start(self):
        logger.info("File IPC Bridge is ready.")

    def start_server(self):
        self.start()

    def send_command(self, cmd_str, timeout=10):
        op = _command_op(cmd_str)
        with self._command_lock:
            lock_fd = self._acquire_ipc_lock(timeout)
            if lock_fd is None:
                return "ERR|LOCK_TIMEOUT"

            try:
                if os.path.exists(self.res_file):
                    try:
                        os.remove(self.res_file)
                    except Exception:
                        pass

                try:
                    with open(self.cmd_file, "w") as f:
                        f.write(cmd_str)
                        f.flush()
                        os.fsync(f.fileno())
                    command_written_at = time.time()
                except Exception as exc:
                    logger.error("Error writing command file: %s", exc)
                    return "ERR|WRITE_FAILED"

                start_time = time.time()
                while time.time() - start_time < timeout:
                    if os.path.exists(self.res_file):
                        try:
                            response_mtime = os.path.getmtime(self.res_file)
                            if response_mtime + 0.001 < command_written_at:
                                os.remove(self.res_file)
                                continue
                            with open(self.res_file, "r") as f:
                                res = f.read().strip()
                            os.remove(self.res_file)
                            if res:
                                if not _response_matches_command(op, res):
                                    logger.warning(
                                        "Ignored stale EA bridge response while waiting for %s: %s",
                                        op,
                                        res,
                                    )
                                    continue
                                return res
                        except Exception:
                            time.sleep(0.05)
                            continue
                    time.sleep(0.1)

                self._clear_command_file()
                return "ERR|TIMEOUT"
            finally:
                self._release_ipc_lock(lock_fd)

    def stop(self):
        pass


ea_bridge = EABridgeServer()
